In [1]:
# 패키지 불러오기
import pandas as pd
import numpy as np
from sklearn import model_selection
from sklearn import metrics
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier

# 데이터 프레임으로 데이터 읽어오기 (latin1 인코딩 시도)
df22 = pd.read_csv(
    "./data/p22v29_KMP_csv.csv",
    encoding="cp1252",
    dtype={"열이름": str}  # 문제가 되는 열을 문자열로 설정
)


# 데이터 크기 출력 및 첫 5행 확인
print(df22.shape)
df22.head(20)

(9941, 533)

/var/folders/tx/ky9fr4hj6bs_8gbgd58q9ty00000gn/T/ipykernel_21229/2640601702.py:11: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df22 = pd.read_csv(

,pid,hid,housenum,p22wt,p22wt2,p22wt_org,p22wt_org2,KMPS10,KMPS11,KMPS19,...,p22e05001,p22e05002,p22e05003,p22e05004,p22e05005,p22e05006,p22e05007,p22e05008,p22e05009,p22e06001
0,10001,100,1,0.109898,.201693923380547,0.218144,2.02401149934543,,1,,...,4,4,4,4,3,3,4,3,2,3
1,10002,100,2,0.093920,.183811940997279,0.214683,1.37034381905224,,1,,...,2,3,1,2,3,2,4,3,4,2
2,10003,100,3,0.145031,,0.362592,,,1,,...,1,1,1,1,1,1,1,1,1,3
3,10004,100,4,0.155248,,0.329126,,,1,,...,3,3,2,2,3,2,3,3,1,1
4,20001,200,1,1.830398,2.04492473325986,1.832333,,,1,,...,2,2,3,2,3,3,2,1,1,4
5,20003,200,3,2.585722,,2.76454,,,1,,...,4,3,4,4,3,2,2,3,2,3
6,30001,300,1,1.125540,1.48331689220196,1.46408,,,1,,...,3,2,2,2,2,2,2,2,2,4
7,30002,300,2,0.927753,1.39281926803057,1.097426,4.27310806630911,,1,,...,2,2,2,2,4,3,4,2,2,4
8,30003,300,3,1.590001,1.60727779712055,2.208937,10.1625825492852,,1,,...,2,1,1,1,3,3,4,2,2,3
9,30004,300,4,1.111026,2.3140970262451,1.283523,,,1,,...,1,1,1,1,1,6,6,1,1,4
10,50001,500,1,0.720588,.944943414653794,0.695975,,,1,,...,3,3,1,3,3,1,4,1,4,3
11,50002,500,2,0.593961,.915199900504768,0.52168,3.4311251631487,,1,,...,3,2,2,2,4,1,3,1,2,3
12,50003,500,3,0.647644,.999343452122968,0.503219,,,1,,...,1,1,1,1,4,6,6,1,1,3
13,50004,500,4,0.647644,1.49238184670279,0.503219,,,1,,...,1,1,1,1,5,6,6,1,1,3
14,60001,600,1,0.361005,.579906143200507,0.889586,,,1,,...,2,2,1,1,4,4,5,2,2,2
15,60002,600,2,0.297566,.495444946053383,0.666804,4.38561878448043,,1,,...,3,3,3,3,2,5,5,2,4,2
16,60003,600,3,0.476245,.557717590032656,1.258943,,,1,,...,1,1,1,1,4,4,5,1,1,1
17,60004,600,4,0.324461,.547157853701119,0.643208,,,1,,...,1,1,1,1,5,6,6,1,1,3
18,80001,800,1,6.383575,6.29547606815348,5.097867,10.2314740897801,,1,,...,1,1,1,5,3,4,5,2,5,2
19,100001,1000,1,2.257901,2.38120510706301,3.648074,9.88291631313977,,1,,...,4,3,1,1,4,5,5,2,2,2